// Copyright (c) Microsoft Corporation. All rights reserved.
// SPDX-License-Identifier: MIT

// Wifi
#define IOT_CONFIG_WIFI_SSID "SSID"
#define IOT_CONFIG_WIFI_PASSWORD "PWD"
#define IOT_CONFIG_WIFI_CONNECT_RETRY_MS 10000

// Azure IoT
#define IOT_CONFIG_IOTHUB_FQDN "[your Azure IoT host name].azure-devices.net"
#define IOT_CONFIG_DEVICE_ID "Device ID"
#define IOT_CONFIG_DEVICE_KEY "Device Key"

// When developing for your own Arduino-based platform,
// please follow the format '(ard;<platform>)'.
#define IOT_CONFIG_AZURE_SDK_CLIENT_USER_AGENT "c/" AZ_SDK_VERSION_STRING "(ard;portentaH7)"

// Publish 1 message every 2 seconds
#define IOT_CONFIG_TELEMETRY_FREQUENCY_MS 2000

// How long a SAS token generated by the sample will be valid, in minutes.
// The sample will stop working after the SAS token is expired, requiring the device to be reset.
#define IOT_CONFIG_SAS_TOKEN_EXPIRY_MINUTES 60

// Time Zone Offset
#define IOT_CONFIG_TIME_ZONE -8
#define IOT_CONFIG_TIME_ZONE_DAYLIGHT_SAVINGS_DIFF 1
#define IOT_CONFIG_DAYLIGHT_SAVINGS true
